# -*- coding: utf-8 -*-
"""Canvas_data_prep.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zYiFGDlADkq6CtXwT1URIjFj3pVyejAM
"""

#Run this in the terminal instead of a Python IDE
!wget http://archive.ics.uci.edu/ml/machine-learning-databases/00254/biodeg.csv



#import dataset of QSAR features and target value
import pandas as pd
df_bio=pd.read_csv("biodeg.csv", sep = ';', header=None)

#Create column names list for dataset

col=[]
for schema in range(len(df_bio.columns)):
  col.append("Val_"+str(schema))

#print(col)

# Assign from the list and Check columnn names
df_bio.columns = col
list(df_bio.columns)

#Assign values for target labels of features
d = {'RB': 1, 'NRB': 0}

df_bio['bio_class']=df_bio.iloc[:,-1].map(d)
#df_bio.drop(df_bio.columns[41],axis=1,inplace=True)

df_bio.head()

df_bio.to_csv('biodeg_qsar_transform.csv')

